[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project]
name = "atom-ml"
description = "A Python package for fast exploration of machine learning pipelines"
authors = [{name = "Mavs", email = "m.524687@gmail.com"}]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.8"
keywords = ["Python package", "Machine Learning", "Modelling", "Data Pipeline"]
dynamic = ["version"]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "category-encoders>=2.4.1",
    "explainerdashboard>=0.4.0",
    "dill>=0.3.5",
    "evalml>=0.58.0",
    "gplearn>=0.4.1",
    "gradio>=3.3.1",
    "imbalanced-learn>=0.9.0",
    "featuretools>=1.14.0",
    "joblib>=1.2.0",
    "matplotlib>=3.5.0, <3.6.0",
    "mlflow>=1.29",
    "nltk>=3.7",
    "numpy>=1.22",
    "optuna>=3.0.0",
    "pandas>=1.3.5",
    "pandas-profiling>=3.3.0",
    "seaborn>=0.12.0",
    "shap>=0.41",
    "schemdraw>=0.14",
    "scikit-learn>=1.1.0",
    "scikit-learn-intelex>=2021.6.3",
    "scipy>=1.8.1",
    "typeguard>=2.13",
    "wordcloud>=1.8.1",
    "zoofs>=0.1.24",
]

[project.urls]
"Documentation" = "https://tvdboom.github.io/ATOM/"
"Issues" = "https://github.com/tvdboom/ATOM/issues"
"Repository" = "https://github.com/tvdboom/ATOM"
"Slack" = "https://join.slack.com/t/atom-alm7229/shared_invite/zt-upd8uc0z-LL63MzBWxFf5tVWOGCBY5g"

[project.optional-dependencies]
models = [
    "catboost>=1.0.4",
    "lightgbm>=3.3.2",
    "xgboost>=1.6.0",
]

[tool.pdm.dev-dependencies]
dev = [
    # Linting
    "isort>=5.10.1",
    "flake8>=5.0.4",
    "flake8-pyproject>=1.1.0",  # To configure flake8 with pyproject.toml
    # Tetsing
    "pytest>=7.1.0",
    "pytest-cov>=3.0.0",
    "tensorflow>=2.3.1",  # To test deep learning pipelines
    # Documentation
    "mike>=1.1.2",  # For versioning
    "mkdocs>=1.2.3",
    "mkdocs-autorefs>=0.4.1",
    "mkdocs-jupyter>=0.22.0",
    "mkdocs-material>=8.5.3",
    "mkdocs-simple-hooks>=0.1.5",
    "pyyaml>=6.0",
]

[tool.pdm.version]
source = "file"
path = "atom/utils.py"

[tool.pdm.build]
includes = ["README.md", "LICENSE", "images/"]
excludes = ["tests/mlruns"]
source-includes = ["tests/"]

[tool.flake8]
max-line-length = 89
ignore = [
    "W605",  # Invalid escape sequence: \s, \w, etc... (removed due to docstrings)
    "W503",  # Line break before binary operator
    "E731",  # Assign a lambda expression
]
per-file-ignores = [
    "__init__.py: F401",  # Imported but unused
    "utils.py: E704",  # Multiple statements on one line (def)
]

[tool.isort]
skip_gitignore = true
multi_line_output = 5
atomic = true
lines_after_imports = 2
include_trailing_comma = true
ignore_comments = true
remove_redundant_aliases = true
